apiVersion: v1
data:
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdSK3d5Rm1hZTdlcnMzaGNDQ3FQSHVUN0lLYnJyYVlnOFphSWJwMk1jNVRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVFY3WWQwcnRneVNVQy8yeXd5VFJ3RmJmUkM2VkRPcnJGc2lLbSs3Qkpzbm5CMVgxVWk1NQpCNkNEeGYwdmQ4NFB1djluZTNSZ3g4TUgwYnlFcHA2UU5nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: "2023-06-19T23:20:34Z"
  labels:
    managed-by: consul-k8s
  name: consul-ca-key
  namespace: consul
  resourceVersion: "642"
  uid: 21ee805c-fb69-4fce-b660-82e632dcbde3
type: Opaque
