apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: cernunnos           ## The name of the partition containing the service
  # namespace: unicorn      # I believe ExportedServices are scoped to partition only.
spec:
  services:
    - name: "unicorn-backend" ## The name of the service you want to export
      namespace: "unicorn"
      consumers:
      - partition: default 
    - name: "unicorn-tp-backend" ## The name of the service you want to export
      namespace: "unicorn"
      consumers:
      - partition: default 
    - name: "mesh-gateway" ## The name of the service you want to export
      namespace: "default"
      consumers:
      - partition: default 
