apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-backend
  namespace: unicorn
spec:
  sources:
    - name: unicorn-frontend
      partition: default
      namespace: unicorn
      action: allow
  destination:
    name: unicorn-backend
    # partition: cernunnos   # partition not used (likely until multi partition within single k8s is supported)
    namespace: unicorn